### Cross Validation Techniques

In [1]:
data = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [4]:
# Hold Out

from sklearn.model_selection import train_test_split

x_train, x_test = train_test_split(data, test_size=0.3)

x_train, x_test

([50, 40, 10, 90, 30, 20, 70], [80, 60, 100])

In [12]:
# Leave One Out

from sklearn.model_selection import LeaveOneOut
import numpy as np

loo = LeaveOneOut()

for train_idxs, test_idxs in loo.split(data):
    print(np.take(data, train_idxs), np.take(data, test_idxs))

[ 20  30  40  50  60  70  80  90 100] [10]
[ 10  30  40  50  60  70  80  90 100] [20]
[ 10  20  40  50  60  70  80  90 100] [30]
[ 10  20  30  50  60  70  80  90 100] [40]
[ 10  20  30  40  60  70  80  90 100] [50]
[ 10  20  30  40  50  70  80  90 100] [60]
[ 10  20  30  40  50  60  80  90 100] [70]
[ 10  20  30  40  50  60  70  90 100] [80]
[ 10  20  30  40  50  60  70  80 100] [90]
[10 20 30 40 50 60 70 80 90] [100]


In [13]:
# Leave P Out

from sklearn.model_selection import LeavePOut

lpo = LeavePOut(2)

for train_idxs, test_idxs in lpo.split(data):
    print(np.take(data, train_idxs), np.take(data, test_idxs))

[ 30  40  50  60  70  80  90 100] [10 20]
[ 20  40  50  60  70  80  90 100] [10 30]
[ 20  30  50  60  70  80  90 100] [10 40]
[ 20  30  40  60  70  80  90 100] [10 50]
[ 20  30  40  50  70  80  90 100] [10 60]
[ 20  30  40  50  60  80  90 100] [10 70]
[ 20  30  40  50  60  70  90 100] [10 80]
[ 20  30  40  50  60  70  80 100] [10 90]
[20 30 40 50 60 70 80 90] [ 10 100]
[ 10  40  50  60  70  80  90 100] [20 30]
[ 10  30  50  60  70  80  90 100] [20 40]
[ 10  30  40  60  70  80  90 100] [20 50]
[ 10  30  40  50  70  80  90 100] [20 60]
[ 10  30  40  50  60  80  90 100] [20 70]
[ 10  30  40  50  60  70  90 100] [20 80]
[ 10  30  40  50  60  70  80 100] [20 90]
[10 30 40 50 60 70 80 90] [ 20 100]
[ 10  20  50  60  70  80  90 100] [30 40]
[ 10  20  40  60  70  80  90 100] [30 50]
[ 10  20  40  50  70  80  90 100] [30 60]
[ 10  20  40  50  60  80  90 100] [30 70]
[ 10  20  40  50  60  70  90 100] [30 80]
[ 10  20  40  50  60  70  80 100] [30 90]
[10 20 40 50 60 70 80 90] [ 30 100]
[ 10  20  

In [19]:
# K-Fold

from sklearn.model_selection import KFold

kf = KFold(n_splits=3)

for train_idxs, test_idxs in kf.split(data):
    print(np.take(data, train_idxs), np.take(data, test_idxs))

[ 50  60  70  80  90 100] [10 20 30 40]
[ 10  20  30  40  80  90 100] [50 60 70]
[10 20 30 40 50 60 70] [ 80  90 100]
