In [1]:
import pandas as pd
import numpy as np

In [2]:
x = [10,20,30,40,50,60,70,80,90,100]
x

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [3]:
# hold out cross validation method
from sklearn.model_selection import train_test_split

In [4]:
x_train, x_test = train_test_split(x, test_size=0.3)

In [5]:
x_train

[10, 60, 50, 70, 80, 30, 20]

In [6]:
x_test

[100, 40, 90]

In [7]:
# leave one out cross validation
from sklearn.model_selection import LeaveOneOut
l = LeaveOneOut()

In [8]:
for train, test in l.split(x):
    print(train, test)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


In [9]:
# leave P out cross validation
from sklearn.model_selection import LeavePOut
lpo = LeavePOut(1)

In [10]:
print(lpo)

LeavePOut(p=1)


In [11]:
x = np.array([[1,2],[3,4],[5,6],[7,8]])
y = np.array([1,2,3,4])
lpo = LeavePOut(2)
for train_index, test_index in lpo.split(x):
    print("Train:", train_index, "Test:", test_index)
    x_train, x_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]

Train: [2 3] Test: [0 1]
Train: [1 3] Test: [0 2]
Train: [1 2] Test: [0 3]
Train: [0 3] Test: [1 2]
Train: [0 2] Test: [1 3]
Train: [0 1] Test: [2 3]


In [12]:
# K fold cross validation
from sklearn.model_selection import KFold
kf = KFold()

In [13]:
x = ['a', 'b', 'c', 'd' ,'e', 'f']
kf = KFold(n_splits = 3, shuffle = False, random_state = None)

for train, test in kf.split(x):
    print("Train data", train, "Test data", test)

Train data [2 3 4 5] Test data [0 1]
Train data [0 1 4 5] Test data [2 3]
Train data [0 1 2 3] Test data [4 5]


In [18]:
# Stratified K fold cross validation
from sklearn.model_selection import StratifiedKFold

In [21]:
x = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
y = np.array([0,0,1,0,1,1])

skf = StratifiedKFold(n_splits = 3, shuffle = False, random_state = None)

for train, test in skf.split(x,y):
    print("Train:", train_index, "Test:", test_index)
    x_train, x_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]

Train: [0 1] Test: [2 3]
Train: [0 1] Test: [2 3]
Train: [0 1] Test: [2 3]
