In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = load_breast_cancer()

In [3]:
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target

df.sample(4)

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
306        13.20         15.82           84.07      537.3          0.08511   
452        12.00         28.23           76.77      442.5          0.08437   
281        11.74         14.02           74.24      427.3          0.07813   
312        12.76         13.37           82.29      504.1          0.08794   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
306           0.05251        0.001461             0.003261         0.1632   
452           0.06450        0.040550             0.019450         0.1615   
281           0.04340        0.022450             0.027630         0.2101   
312           0.07948        0.040520             0.025480         0.1601   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
306                 0.05894  ...          20.45            92.00       636.9   
452                 0.06104  ...          37.88            85.07       523.7   
281                 0.06113  ...          18.26            84.70       533.7   
312                 0.06140  ...          16.40            92.04       618.8   

     worst smoothness  worst compactness  worst concavity  \
306            0.1128             0.1346          0.01120   
452            0.1208             0.1856          0.18110   
281            0.1036             0.0850          0.06735   
312            0.1194             0.2208          0.17690   

     worst concave points  worst symmetry  worst fractal dimension  target  
306               0.02500          0.2651                  0.08385       1  
452               0.07116          0.2447                  0.08194       1  
281               0.08290          0.3101                  0.06688       1  
312               0.08411          0.2564                  0.08253       1  

[4 rows x 31 columns]

In [4]:
df.shape

(569, 31)

In [5]:
sample_1 = df.sample(200, replace = True)
sample_2 = df.sample(200, replace = True)
sample_3 = df.sample(200, replace = True)

In [6]:
sample_1.shape

(200, 31)

In [7]:
from sklearn.tree import DecisionTreeClassifier

In [8]:
base_model_1 = DecisionTreeClassifier(max_depth=2)
base_model_2 = DecisionTreeClassifier(max_depth=2)
base_model_3 = DecisionTreeClassifier(max_depth=2)

In [9]:
base_model_1

DecisionTreeClassifier(max_depth=2)

In [10]:
sample_1.iloc[:,:30]

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
269        10.71         20.39           69.50      344.9          0.10820   
342        11.06         14.96           71.49      373.9          0.10330   
32         17.02         23.98          112.80      899.3          0.11970   
567        20.60         29.33          140.10     1265.0          0.11780   
65         14.78         23.94           97.40      668.3          0.11720   
..           ...           ...             ...        ...              ...   
326        14.11         12.88           90.03      616.5          0.09309   
481        13.90         19.24           88.73      602.9          0.07991   
284        12.89         15.70           84.08      516.6          0.07818   
47         13.17         18.66           85.98      534.6          0.11580   
549        10.82         24.21           68.89      361.6          0.08192   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
269           0.12890         0.08448              0.02867         0.1668   
342           0.09097         0.05397              0.03341         0.1776   
32            0.14960         0.24170              0.12030         0.2248   
567           0.27700         0.35140              0.15200         0.2397   
65            0.14790         0.12670              0.09029         0.1953   
..                ...             ...                  ...            ...   
326           0.05306         0.01765              0.02733         0.1373   
481           0.05326         0.02995              0.02070         0.1579   
284           0.09580         0.11150              0.03390         0.1432   
47            0.12310         0.12260              0.07340         0.2128   
549           0.06602         0.01548              0.00816         0.1976   

     mean fractal dimension  ...  worst radius  worst texture  \
269                 0.06862  ...         11.69          25.21   
342                 0.06907  ...         11.92          19.90   
32                  0.06382  ...         20.88          32.09   
567                 0.07016  ...         25.74          39.42   
65                  0.06654  ...         17.31          33.39   
..                      ...  ...           ...            ...   
326                 0.05700  ...         15.53          18.00   
481                 0.05594  ...         16.41          26.42   
284                 0.05935  ...         13.90          19.69   
47                  0.06777  ...         15.67          27.95   
549                 0.06328  ...         13.03          31.45   

     worst perimeter  worst area  worst smoothness  worst compactness  \
269            76.51       410.4           0.13350             0.2550   
342            79.76       440.0           0.14180             0.2210   
32            136.10      1344.0           0.16340             0.3559   
567           184.60      1821.0           0.16500             0.8681   
65            114.60       925.1           0.16480             0.3416   
..               ...         ...               ...                ...   
326            98.40       749.9           0.12810             0.1109   
481           104.40       830.5           0.10640             0.1415   
284            92.12       595.6           0.09926             0.2317   
47            102.80       759.4           0.17860             0.4166   
549            83.90       505.6           0.12040             0.1633   

     worst concavity  worst concave points  worst symmetry  \
269          0.25340               0.08600          0.2605   
342          0.22990               0.10750          0.3301   
32           0.55880               0.18470          0.3530   
567          0.93870               0.26500          0.4087   
65           0.30240               0.16140          0.3321   
..               ...                   ...             ...   
326          0.05307               0.05890         

In [11]:
base_model_1.fit(sample_1.iloc[:,:30],sample_1.iloc[:,-1])
base_model_2.fit(sample_2.iloc[:,:30],sample_2.iloc[:,-1])
base_model_3.fit(sample_3.iloc[:,:30],sample_3.iloc[:,-1])

DecisionTreeClassifier(max_depth=2)

In [12]:
for i in df.sample():
    print(i)

mean radius
mean texture
mean perimeter
mean area
mean smoothness
mean compactness
mean concavity
mean concave points
mean symmetry
mean fractal dimension
radius error
texture error
perimeter error
area error
smoothness error
compactness error
concavity error
concave points error
symmetry error
fractal dimension error
worst radius
worst texture
worst perimeter
worst area
worst smoothness
worst compactness
worst concavity
worst concave points
worst symmetry
worst fractal dimension
target


In [13]:
df.sample().values

array([[2.073e+01, 3.112e+01, 1.357e+02, 1.419e+03, 9.469e-02, 1.143e-01,
        1.367e-01, 8.646e-02, 1.769e-01, 5.674e-02, 1.172e+00, 1.617e+00,
        7.749e+00, 1.997e+02, 4.551e-03, 1.478e-02, 2.143e-02, 9.280e-03,
        1.367e-02, 2.299e-03, 3.249e+01, 4.716e+01, 2.140e+02, 3.432e+03,
        1.401e-01, 2.644e-01, 3.442e-01, 1.659e-01, 2.868e-01, 8.218e-02,
        0.000e+00]])

In [14]:
df.drop(df['target'].values)

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
5          12.45         15.70           82.57      477.1          0.12780   
6          18.25         19.98          119.60     1040.0          0.09463   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
5             0.17000         0.15780              0.08089         0.2087   
6             0.10900         0.11270              0.07400         0.1794   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
2                   0.05999  ...          25.53           152.50      1709.0   
3                   0.09744  ...          26.50            98.87       567.7   
4                   0.05883  ...          16.67           152.20      1575.0   
5                   0.07613  ...          23.75           103.40       741.6   
6                   0.05742  ...          27.66           153.20      1606.0   
..                      ...  ...            ...              ...         ...   
564                 0.05623  ...          26.40           166.10      2027.0   
565                 0.05533  ...          38.25           155.00      1731.0   
566                 0.05648  ...          34.12           126.70      1124.0   
567                 0.07016  ...          39.42           184.60      1821.0   
568                 0.05884  ...          30.37            59.16       268.6   

     worst smoothness  worst compactness  worst concavity  \
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
5             0.17910            0.52490           0.5355   
6             0.14420            0.25760           0.3784   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     worst concave points  worst symmetry  worst fractal dimension  target  
2                  0.2430          0.3613                  0.08758       0  
3                  0.2575          0.6638                  0.17300       0  
4                  0.1625          0.2364                  0.07678       0  
5                  0.1741          0.3985                  0.12440       0  
6                  0.1932          0.3063                  0.083

In [22]:
sample_ = df.iloc[:,:30].sample(1).values

In [16]:
#base_model_1.predict(df.iloc[:,:30].sample(1).values)

In [23]:
base_model_1.predict(sample_)

array([0])

In [24]:
base_model_2.predict(sample_)

array([0])

In [25]:
base_model_3.predict(sample_)

array([0])